In [8]:
import numpy as np

In [9]:
X=np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]])
y=np.array([[1],[5],[6],[8]])

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
model=LinearRegression()

In [10]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [15]:
model.intercept_

array([-0.14285714])

In [16]:
model.score(X,y) #予測精度←決定係数

0.6923076923076926

In [17]:
x=np.array([[1,2,3]])

In [18]:
y_pred=model.predict(x)
y_pred

array([[3.]])