In [1]:
import numpy as np

In [3]:
x=np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [6]:
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [7]:
#転置

In [8]:
X.T
print(X.T)

[[1 3]
 [2 4]]


In [9]:
#逆行列→numpyのliner algebraを使う（np.linalg.inv）

In [13]:
Xi=np.linalg.inv(X)
print(Xi)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
#行列積

In [16]:
XX=np.dot(X,Xi)
print(XX)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [34]:
X=np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]])
y=np.array([[1],[5],[6],[8]]) #二重括弧は縦ベクトル表記するため
print(X)
print(y)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]
[[1]
 [5]
 [6]
 [8]]


In [27]:
Xt=X.T

In [28]:
XtX=np.dot(Xt,X)

In [36]:
XtX_i=np.linalg.inv(XtX)
print(XtX_i)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [35]:
Xty=np.dot(Xt,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [33]:
w=np.dot(XtX_i,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]
